// megafunction wizard: %FIFO%
// GENERATION: STANDARD
// VERSION: WM1.0
// MODULE: dcfifo 

// ============================================================
// File Name: FIFO.v
// Megafunction Name(s):
// 			dcfifo
//
// Simulation Library Files(s):
// 			altera_mf
// ============================================================
// ************************************************************
// THIS IS A WIZARD-GENERATED FILE. DO NOT EDIT THIS FILE!
//
// 16.0.0 Build 211 04/27/2016 SJ Lite Edition
// ************************************************************


//Copyright (C) 1991-2016 Altera Corporation. All rights reserved.
//Your use of Altera Corporation's design tools, logic functions 
//and other software and tools, and its AMPP partner logic 
//functions, and any output files from any of the foregoing 
//(including device programming or simulation files), and any 
//associated documentation or information are expressly subject 
//to the terms and conditions of the Altera Program License 
//Subscription Agreement, the Altera Quartus Prime License Agreement,
//the Altera MegaCore Function License Agreement, or other 
//applicable license agreement, including, without limitation, 
//that your use is for the sole purpose of programming logic 
//devices manufactured by Altera and sold by Altera or its 
//authorized distributors.  Please refer to the applicable 
//agreement for further details.


//dcfifo_mixed_widths DEVICE_FAMILY="Cyclone IV E" LPM_NUMWORDS=128 LPM_SHOWAHEAD="ON" LPM_WIDTH=8 LPM_WIDTH_R=8 LPM_WIDTHU=7 LPM_WIDTHU_R=7 OVERFLOW_CHECKING="ON" RDSYNC_DELAYPIPE=3 UNDERFLOW_CHECKING="ON" USE_EAB="ON" WRSYNC_DELAYPIPE=3 data q rdclk rdempty rdreq wrclk wrfull wrreq INTENDED_DEVICE_FAMILY="Cyclone IV E" ALTERA_INTERNAL_OPTIONS=AUTO_SHIFT_REGISTER_RECOGNITION=OFF
//VERSION_BEGIN 16.0 cbx_a_gray2bin 2016:04:27:18:05:34:SJ cbx_a_graycounter 2016:04:27:18:05:34:SJ cbx_altdpram 2016:04:27:18:05:34:SJ cbx_altera_syncram 2016:04:27:18:05:34:SJ cbx_altera_syncram_nd_impl 2016:04:27:18:05:34:SJ cbx_altsyncram 2016:04:27:18:05:34:SJ cbx_cycloneii 2016:04:27:18:05:34:SJ cbx_dcfifo 2016:04:27:18:05:34:SJ cbx_fifo_common 2016:04:27:18:05:34:SJ cbx_lpm_add_sub 2016:04:27:18:05:34:SJ cbx_lpm_compare 2016:04:27:18:05:34:SJ cbx_lpm_counter 2016:04:27:18:05:34:SJ cbx_lpm_decode 2016:04:27:18:05:34:SJ cbx_lpm_mux 2016:04:27:18:05:34:SJ cbx_mgl 2016:04:27:18:06:48:SJ cbx_nadder 2016:04:27:18:05:34:SJ cbx_scfifo 2016:04:27:18:05:34:SJ cbx_stratix 2016:04:27:18:05:34:SJ cbx_stratixii 2016:04:27:18:05:34:SJ cbx_stratixiii 2016:04:27:18:05:34:SJ cbx_stratixv 2016:04:27:18:05:34:SJ cbx_util_mgl 2016:04:27:18:05:34:SJ  VERSION_END
// synthesis VERILOG_INPUT_VERSION VERILOG_2001
// altera message_off 10463



//a_graycounter DEVICE_FAMILY="Cyclone IV E" PVALUE=1 WIDTH=8 clock cnt_en q
//VERSION_BEGIN 16.0 cbx_a_gray2bin 2016:04:27:18:05:34:SJ cbx_a_graycounter 2016:04:27:18:05:34:SJ cbx_cycloneii 2016:04:27:18:05:34:SJ cbx_mgl 2016:04:27:18:06:48:SJ cbx_stratix 2016:04:27:18:05:34:SJ cbx_stratixii 2016:04:27:18:05:34:SJ  VERSION_END

//synthesis_resources = reg 11 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
(* ALTERA_ATTRIBUTE = {"{-to counter1a[0]} POWER_UP_LEVEL=HIGH"} *)
module  FIFO_a_graycounter
	( 
	clock,
	cnt_en,
	q) /* synthesis synthesis_clearbox=1 */;
	input   clock;
	input   cnt_en;
	output   [7:0]  q;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri1   cnt_en;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	reg	[7:0]	counter1a;
	(* ALTERA_ATTRIBUTE = {"POWER_UP_LEVEL=HIGH"} *)
	reg	parity2;
	reg	[1:0]	sub_parity3a;
	wire  [7:0]  cntr_cout;
	wire  parity_cout;
	wire sclr;
	wire updown;

	// synopsys translate_off
	initial
		counter1a[0:0] = {1{1'b1}};
	// synopsys translate_on
	always @ ( posedge clock)
		
			if (sclr == 1'b1) counter1a[0:0] <= 1'b0;
			else  counter1a[0:0] <= ((cnt_en & (counter1a[0:0] ^ (~ parity_cout))) | ((~ cnt_en) & counter1a[0:0]));
	// synopsys translate_off
	initial
		counter1a[1:1] = 0;
	// synopsys translate_on
	always @ ( posedge clock)
		
			if (sclr == 1'b1) counter1a[1:1] <= 1'b0;
			else  counter1a[1:1] <= (counter1a[1:1] ^ (counter1a[0:0] & cntr_cout[0]));
	// synopsys translate_off
	initial
		counter1a[2:2] = 0;
	// synopsys translate_on
	always @ ( posedge clock)
		
			if (sclr == 1'b1) counter1a[2:2] <= 1'b0;
			else  counter1a[2:2] <= (counter1a[2:2] ^ (counter1a[1:1] & cntr_cout[1]));
	// synopsys translate_off
	initial
		counter1a[3:3] = 0;
	// synopsys translate_on
	always @ ( posedge clock)
		
			if (sclr == 1'b1) counter1a[3:3] <= 1'b0;
			else  counter1a[3:3] <= (counter1a[3:3] ^ (counter1a[2:2] & cntr_cout[2]));
	// synopsys translate_off
	initial
		counter1a[4:4] = 0;
	// synopsys translate_on
	always @ ( posedge clock)
		
			if (sclr == 1'b1) counter1a[4:4] <= 1'b0;
			else  counter1a[4:4] <= (counter1a[4:4] ^ (counter1a[3:3] & cntr_cout[3]));
	// synopsys translate_off
	initial
		counter1a[5:5] = 0;
	// synopsys translate_on
	always @ ( posedge clock)
		
			if (sclr == 1'b1) counter1a[5:5] <= 1'b0;
			else  counter1a[5:5] <= (counter1a[5:5] ^ (counter1a[4:4] & cntr_cout[4]));
	// synopsys translate_off
	initial
		counter1a[6:6] = 0;
	// synopsys translate_on
	always @ ( posedge clock)
		
			if (sclr == 1'b1) counter1a[6:6] <= 1'b0;
			else  counter1a[6:6] <= (counter1a[6:6] ^ (counter1a[5:5] & cntr_cout[5]));
	// synopsys translate_off
	initial
		counter1a[7:7] = 0;
	// synopsys translate_on
	always @ ( posedge clock)
		
			if (sclr == 1'b1) counter1a[7:7] <= 1'b0;
			else  counter1a[7:7] <= (counter1a[7:7] ^ cntr_cout[6]);
	// synopsys translate_off
	initial
		parity2 = {1{1'b1}};
	// synopsys translate_on
	always @ ( posedge clock)
		
			if (sclr == 1'b1) parity2 <= 1'b0;
			else  parity2 <= ((cnt_en & (sub_parity3a[0] ^ sub_parity3a[1])) | ((~ cnt_en) & parity2));
	// synopsys translate_off
	initial
		sub_parity3a[0:0] = 0;
	// synopsys translate_on
	always @ ( posedge clock)
		
			if (sclr == 1'b1) sub_parity3a[0:0] <= 1'b0;
			else  sub_parity3a[0:0] <= ((cnt_en & (((counter1a[0] ^ counter1a[1]) ^ counter1a[2]) ^ counter1a[3])) | ((~ cnt_en) & sub_parity3a[0:0]));
	// synopsys translate_off
	initial
		sub_parity3a[1:1] = 0;
	// synopsys translate_on
	always @ ( posedge clock)
		
			if (sclr == 1'b1) sub_parity3a[1:1] <= 1'b0;
			else  sub_parity3a[1:1] <= ((cnt_en & (((counter1a[4] ^ counter1a[5]) ^ counter1a[6]) ^ counter1a[7])) | ((~ cnt_en) & sub_parity3a[1:1]));
	assign
		cntr_cout = {1'b0, (cntr_cout[5] & (~ counter1a[5:5])), (cntr_cout[4] & (~ counter1a[4:4])), (cntr_cout[3] & (~ counter1a[3:3])), (cntr_cout[2] & (~ counter1a[2:2])), (cntr_cout[1] & (~ counter1a[1:1])), (cntr_cout[0] & (~ counter1a[0:0])), (cnt_en & parity_cout)},
		parity_cout = (((~ parity2) ^ updown) & cnt_en),
		q = counter1a,
		sclr = 1'b0,
		updown = 1'b1;
endmodule //FIFO_a_graycounter


//a_graycounter DEVICE_FAMILY="Cyclone IV E" PVALUE=1 WIDTH=8 clock cnt_en q ALTERA_INTERNAL_OPTIONS=suppress_da_rule_internal=S102
//VERSION_BEGIN 16.0 cbx_a_gray2bin 2016:04:27:18:05:34:SJ cbx_a_graycounter 2016:04:27:18:05:34:SJ cbx_cycloneii 2016:04:27:18:05:34:SJ cbx_mgl 2016:04:27:18:06:48:SJ cbx_stratix 2016:04:27:18:05:34:SJ cbx_stratixii 2016:04:27:18:05:34:SJ  VERSION_END

//synthesis_resources = reg 11 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
(* ALTERA_ATTRIBUTE = {"suppress_da_rule_internal=S102;{-to counter4a[0]} POWER_UP_LEVEL=HIGH"} *)
module  FIFO_a_graycounter1
	( 
	clock,
	cnt_en,
	q) /* synthesis synthesis_clearbox=1 */;
	input   clock;
	input   cnt_en;
	output   [7:0]  q;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri1   cnt_en;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	reg	[7:0]	counter4a;
	(* ALTERA_ATTRIBUTE = {"POWER_UP_LEVEL=HIGH"} *)
	reg	parity5;
	reg	[1:0]	sub_parity6a;
	wire  [7:0]  cntr_cout;
	wire  parity_cout;
	wire sclr;
	wire updown;

	// synopsys translate_off
	initial
		counter4a[0:0] = {1{1'b1}};
	// synopsys translate_on
	always @ ( posedge clock)
		
			if (sclr == 1'b1) counter4a[0:0] <= 1'b0;
			else  counter4a[0:0] <= ((cnt_en & (counter4a[0:0] ^ (~ parity_cout))) | ((~ cnt_en) & counter4a[0:0]));
	// synopsys translate_off
	initial
		counter4a[1:1] = 0;
	// synopsys translate_on
	always @ ( posedge clock)
		
			if (sclr == 1'b1) counter4a[1:1] <= 1'b0;
			else  counter4a[1:1] <= (counter4a[1:1] ^ (counter4a[0:0] & cntr_cout[0]));
	// synopsys translate_off
	initial
		counter4a[2:2] = 0;
	// synopsys translate_on
	always @ ( posedge clock)
		
			if (sclr == 1'b1) counter4a[2:2] <= 1'b0;
			else  counter4a[2:2] <= (counter4a[2:2] ^ (counter4a[1:1] & cntr_cout[1]));
	// synopsys translate_off
	initial
		counter4a[3:3] = 0;
	// synopsys translate_on
	always @ ( posedge clock)
		
			if (sclr == 1'b1) counter4a[3:3] <= 1'b0;
			else  counter4a[3:3] <= (counter4a[3:3] ^ (counter4a[2:2] & cntr_cout[2]));
	// synopsys translate_off
	initial
		counter4a[4:4] = 0;
	// synopsys translate_on
	always @ ( posedge clock)
		
			if (sclr == 1'b1) counter4a[4:4] <= 1'b0;
			else  counter4a[4:4] <= (counter4a[4:4] ^ (counter4a[3:3] & cntr_cout[3]));
	// synopsys translate_off
	initial
		counter4a[5:5] = 0;
	// synopsys translate_on
	always @ ( posedge clock)
		
			if (sclr == 1'b1) counter4a[5:5] <= 1'b0;
			else  counter4a[5:5] <= (counter4a[5:5] ^ (counter4a[4:4] & cntr_cout[4]));
	// synopsys translate_off
	initial
		counter4a[6:6] = 0;
	// synopsys translate_on
	always @ ( posedge clock)
		
			if (sclr == 1'b1) counter4a[6:6] <= 1'b0;
			else  counter4a[6:6] <= (counter4a[6:6] ^ (counter4a[5:5] & cntr_cout[5]));
	// synopsys translate_off
	initial
		counter4a[7:7] = 0;
	// synopsys translate_on
	always @ ( posedge clock)
		
			if (sclr == 1'b1) counter4a[7:7] <= 1'b0;
			else  counter4a[7:7] <= (counter4a[7:7] ^ cntr_cout[6]);
	// synopsys translate_off
	initial
		parity5 = {1{1'b1}};
	// synopsys translate_on
	always @ ( posedge clock)
		
			if (sclr == 1'b1) parity5 <= 1'b0;
			else  parity5 <= ((cnt_en & (sub_parity6a[0] ^ sub_parity6a[1])) | ((~ cnt_en) & parity5));
	// synopsys translate_off
	initial
		sub_parity6a[0:0] = 0;
	// synopsys translate_on
	always @ ( posedge clock)
		
			if (sclr == 1'b1) sub_parity6a[0:0] <= 1'b0;
			else  sub_parity6a[0:0] <= ((cnt_en & (((counter4a[0] ^ counter4a[1]) ^ counter4a[2]) ^ counter4a[3])) | ((~ cnt_en) & sub_parity6a[0:0]));
	// synopsys translate_off
	initial
		sub_parity6a[1:1] = 0;
	// synopsys translate_on
	always @ ( posedge clock)
		
			if (sclr == 1'b1) sub_parity6a[1:1] <= 1'b0;
			else  sub_parity6a[1:1] <= ((cnt_en & (((counter4a[4] ^ counter4a[5]) ^ counter4a[6]) ^ counter4a[7])) | ((~ cnt_en) & sub_parity6a[1:1]));
	assign
		cntr_cout = {1'b0, (cntr_cout[5] & (~ counter4a[5:5])), (cntr_cout[4] & (~ counter4a[4:4])), (cntr_cout[3] & (~ counter4a[3:3])), (cntr_cout[2] & (~ counter4a[2:2])), (cntr_cout[1] & (~ counter4a[1:1])), (cntr_cout[0] & (~ counter4a[0:0])), (cnt_en & parity_cout)},
		parity_cout = (((~ parity5) ^ updown) & cnt_en),
		q = counter4a,
		sclr = 1'b0,
		updown = 1'b1;
endmodule //FIFO_a_graycounter1


//altsyncram ADDRESS_REG_B="CLOCK1" CLOCK_ENABLE_INPUT_B="BYPASS" DEVICE_FAMILY="Cyclone IV E" ENABLE_ECC="FALSE" OPERATION_MODE="DUAL_PORT" OUTDATA_REG_B="UNREGISTERED" WIDTH_A=8 WIDTH_B=8 WIDTH_BYTEENA_A=1 WIDTH_ECCSTATUS=2 WIDTHAD_A=7 WIDTHAD_B=7 address_a address_b addressstall_b clock0 clock1 data_a q_b wren_a
//VERSION_BEGIN 16.0 cbx_altera_syncram_nd_impl 2016:04:27:18:05:34:SJ cbx_altsyncram 2016:04:27:18:05:34:SJ cbx_cycloneii 2016:04:27:18:05:34:SJ cbx_lpm_add_sub 2016:04:27:18:05:34:SJ cbx_lpm_compare 2016:04:27:18:05:34:SJ cbx_lpm_decode 2016:04:27:18:05:34:SJ cbx_lpm_mux 2016:04:27:18:05:34:SJ cbx_mgl 2016:04:27:18:06:48:SJ cbx_nadder 2016:04:27:18:05:34:SJ cbx_stratix 2016:04:27:18:05:34:SJ cbx_stratixii 2016:04:27:18:05:34:SJ cbx_stratixiii 2016:04:27:18:05:34:SJ cbx_stratixv 2016:04:27:18:05:34:SJ cbx_util_mgl 2016:04:27:18:05:34:SJ  VERSION_END

//synthesis_resources = M9K 1 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
(* ALTERA_ATTRIBUTE = {"OPTIMIZE_POWER_DURING_SYNTHESIS=NORMAL_COMPILATION"} *)
module  FIFO_altsyncram
	( 
	address_a,
	address_b,
	addressstall_b,
	clock0,
	clock1,
	data_a,
	q_b,
	wren_a) /* synthesis synthesis_clearbox=1 */;
	input   [6:0]  address_a;
	input   [6:0]  address_b;
	input   addressstall_b;
	input   clock0;
	input   clock1;
	input   [7:0]  data_a;
	output   [7:0]  q_b;
	input   wren_a;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri1   [6:0]  address_b;
	tri0   addressstall_b;
	tri1   clock0;
	tri1   clock1;
	tri1   [7:0]  data_a;
	tri0   wren_a;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	wire  [0:0]   wire_ram_block7a_0portbdataout;
	wire  [0:0]   wire_ram_block7a_1portbdataout;
	wire  [0:0]   wire_ram_block7a_2portbdataout;
	wire  [0:0]   wire_ram_block7a_3portbdataout;
	wire  [0:0]   wire_ram_block7a_4portbdataout;
	wire  [0:0]   wire_ram_block7a_5portbdataout;
	wire  [0:0]   wire_ram_block7a_6portbdataout;
	wire  [0:0]   wire_ram_block7a_7portbdataout;
	wire  [6:0]  address_a_wire;
	wire  [6:0]  address_b_wire;

	cycloneive_ram_block   ram_block7a_0
	( 
	.clk0(clock0),
	.clk1(clock1),
	.ena0(wren_a),
	.portaaddr({address_a_wire[6:0]}),
	.portadatain({data_a[0]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[6:0]}),
	.portbaddrstall(addressstall_b),
	.portbdataout(wire_ram_block7a_0portbdataout[0:0]),
	.portbre(1'b1)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portare(1'b1),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block7a_0.clk0_core_clock_enable = "ena0",
		ram_block7a_0.clk0_input_clock_enable = "none",
		ram_block7a_0.clk1_core_clock_enable = "none",
		ram_block7a_0.clk1_input_clock_enable = "none",
		ram_block7a_0.connectivity_checking = "OFF",
		ram_block7a_0.logical_ram_name = "ALTSYNCRAM",
		ram_block7a_0.mixed_port_feed_through_mode = "dont_care",
		ram_block7a_0.operation_mode = "dual_port",
		ram_block7a_0.port_a_address_width = 7,
		ram_block7a_0.port_a_data_width = 1,
		ram_block7a_0.port_a_first_address = 0,
		ram_block7a_0.port_a_first_bit_number = 0,
		ram_block7a_0.port_a_last_address = 127,
		ram_block7a_0.port_a_logical_ram_depth = 128,
		ram_block7a_0.port_a_logical_ram_width = 8,
		ram_block7a_0.port_b_address_clear = "none",
		ram_block7a_0.port_b_address_clock = "clock1",
		ram_block7a_0.port_b_address_width = 7,
		ram_block7a_0.port_b_data_out_clear = "none",
		ram_block7a_0.port_b_data_width = 1,
		ram_block7a_0.port_b_first_address = 0,
		ram_block7a_0.port_b_first_bit_number = 0,
		ram_block7a_0.port_b_last_address = 127,
		ram_block7a_0.port_b_logical_ram_depth = 128,
		ram_block7a_0.port_b_logical_ram_width = 8,
		ram_block7a_0.port_b_read_enable_clock = "clock1",
		ram_block7a_0.ram_block_type = "AUTO",
		ram_block7a_0.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block7a_1
	( 
	.clk0(clock0),
	.clk1(clock1),
	.ena0(wren_a),
	.portaaddr({address_a_wire[6:0]}),
	.portadatain({data_a[1]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[6:0]}),
	.portbaddrstall(addressstall_b),
	.portbdataout(wire_ram_block7a_1portbdataout[0:0]),
	.portbre(1'b1)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portare(1'b1),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block7a_1.clk0_core_clock_enable = "ena0",
		ram_block7a_1.clk0_input_clock_enable = "none",
		ram_block7a_1.clk1_core_clock_enable = "none",
		ram_block7a_1.clk1_input_clock_enable = "none",
		ram_block7a_1.connectivity_checking = "OFF",
		ram_block7a_1.logical_ram_name = "ALTSYNCRAM",
		ram_block7a_1.mixed_port_feed_through_mode = "dont_care",
		ram_block7a_1.operation_mode = "dual_port",
		ram_block7a_1.port_a_address_width = 7,
		ram_block7a_1.port_a_data_width = 1,
		ram_block7a_1.port_a_first_address = 0,
		ram_block7a_1.port_a_first_bit_number = 1,
		ram_block7a_1.port_a_last_address = 127,
		ram_block7a_1.port_a_logical_ram_depth = 128,
		ram_block7a_1.port_a_logical_ram_width = 8,
		ram_block7a_1.port_b_address_clear = "none",
		ram_block7a_1.port_b_address_clock = "clock1",
		ram_block7a_1.port_b_address_width = 7,
		ram_block7a_1.port_b_data_out_clear = "none",
		ram_block7a_1.port_b_data_width = 1,
		ram_block7a_1.port_b_first_address = 0,
		ram_block7a_1.port_b_first_bit_number = 1,
		ram_block7a_1.port_b_last_address = 127,
		ram_block7a_1.port_b_logical_ram_depth = 128,
		ram_block7a_1.port_b_logical_ram_width = 8,
		ram_block7a_1.port_b_read_enable_clock = "clock1",
		ram_block7a_1.ram_block_type = "AUTO",
		ram_block7a_1.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block7a_2
	( 
	.clk0(clock0),
	.clk1(clock1),
	.ena0(wren_a),
	.portaaddr({address_a_wire[6:0]}),
	.portadatain({data_a[2]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[6:0]}),
	.portbaddrstall(addressstall_b),
	.portbdataout(wire_ram_block7a_2portbdataout[0:0]),
	.portbre(1'b1)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portare(1'b1),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block7a_2.clk0_core_clock_enable = "ena0",
		ram_block7a_2.clk0_input_clock_enable = "none",
		ram_block7a_2.clk1_core_clock_enable = "none",
		ram_block7a_2.clk1_input_clock_enable = "none",
		ram_block7a_2.connectivity_checking = "OFF",
		ram_block7a_2.logical_ram_name = "ALTSYNCRAM",
		ram_block7a_2.mixed_port_feed_through_mode = "dont_care",
		ram_block7a_2.operation_mode = "dual_port",
		ram_block7a_2.port_a_address_width = 7,
		ram_block7a_2.port_a_data_width = 1,
		ram_block7a_2.port_a_first_address = 0,
		ram_block7a_2.port_a_first_bit_number = 2,
		ram_block7a_2.port_a_last_address = 127,
		ram_block7a_2.port_a_logical_ram_depth = 128,
		ram_block7a_2.port_a_logical_ram_width = 8,
		ram_block7a_2.port_b_address_clear = "none",
		ram_block7a_2.port_b_address_clock = "clock1",
		ram_block7a_2.port_b_address_width = 7,
		ram_block7a_2.port_b_data_out_clear = "none",
		ram_block7a_2.port_b_data_width = 1,
		ram_block7a_2.port_b_first_address = 0,
		ram_block7a_2.port_b_first_bit_number = 2,
		ram_block7a_2.port_b_last_address = 127,
		ram_block7a_2.port_b_logical_ram_depth = 128,
		ram_block7a_2.port_b_logical_ram_width = 8,
		ram_block7a_2.port_b_read_enable_clock = "clock1",
		ram_block7a_2.ram_block_type = "AUTO",
		ram_block7a_2.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block7a_3
	( 
	.clk0(clock0),
	.clk1(clock1),
	.ena0(wren_a),
	.portaaddr({address_a_wire[6:0]}),
	.portadatain({data_a[3]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[6:0]}),
	.portbaddrstall(addressstall_b),
	.portbdataout(wire_ram_block7a_3portbdataout[0:0]),
	.portbre(1'b1)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portare(1'b1),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block7a_3.clk0_core_clock_enable = "ena0",
		ram_block7a_3.clk0_input_clock_enable = "none",
		ram_block7a_3.clk1_core_clock_enable = "none",
		ram_block7a_3.clk1_input_clock_enable = "none",
		ram_block7a_3.connectivity_checking = "OFF",
		ram_block7a_3.logical_ram_name = "ALTSYNCRAM",
		ram_block7a_3.mixed_port_feed_through_mode = "dont_care",
		ram_block7a_3.operation_mode = "dual_port",
		ram_block7a_3.port_a_address_width = 7,
		ram_block7a_3.port_a_data_width = 1,
		ram_block7a_3.port_a_first_address = 0,
		ram_block7a_3.port_a_first_bit_number = 3,
		ram_block7a_3.port_a_last_address = 127,
		ram_block7a_3.port_a_logical_ram_depth = 128,
		ram_block7a_3.port_a_logical_ram_width = 8,
		ram_block7a_3.port_b_address_clear = "none",
		ram_block7a_3.port_b_address_clock = "clock1",
		ram_block7a_3.port_b_address_width = 7,
		ram_block7a_3.port_b_data_out_clear = "none",
		ram_block7a_3.port_b_data_width = 1,
		ram_block7a_3.port_b_first_address = 0,
		ram_block7a_3.port_b_first_bit_number = 3,
		ram_block7a_3.port_b_last_address = 127,
		ram_block7a_3.port_b_logical_ram_depth = 128,
		ram_block7a_3.port_b_logical_ram_width = 8,
		ram_block7a_3.port_b_read_enable_clock = "clock1",
		ram_block7a_3.ram_block_type = "AUTO",
		ram_block7a_3.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block7a_4
	( 
	.clk0(clock0),
	.clk1(clock1),
	.ena0(wren_a),
	.portaaddr({address_a_wire[6:0]}),
	.portadatain({data_a[4]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[6:0]}),
	.portbaddrstall(addressstall_b),
	.portbdataout(wire_ram_block7a_4portbdataout[0:0]),
	.portbre(1'b1)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portare(1'b1),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block7a_4.clk0_core_clock_enable = "ena0",
		ram_block7a_4.clk0_input_clock_enable = "none",
		ram_block7a_4.clk1_core_clock_enable = "none",
		ram_block7a_4.clk1_input_clock_enable = "none",
		ram_block7a_4.connectivity_checking = "OFF",
		ram_block7a_4.logical_ram_name = "ALTSYNCRAM",
		ram_block7a_4.mixed_port_feed_through_mode = "dont_care",
		ram_block7a_4.operation_mode = "dual_port",
		ram_block7a_4.port_a_address_width = 7,
		ram_block7a_4.port_a_data_width = 1,
		ram_block7a_4.port_a_first_address = 0,
		ram_block7a_4.port_a_first_bit_number = 4,
		ram_block7a_4.port_a_last_address = 127,
		ram_block7a_4.port_a_logical_ram_depth = 128,
		ram_block7a_4.port_a_logical_ram_width = 8,
		ram_block7a_4.port_b_address_clear = "none",
		ram_block7a_4.port_b_address_clock = "clock1",
		ram_block7a_4.port_b_address_width = 7,
		ram_block7a_4.port_b_data_out_clear = "none",
		ram_block7a_4.port_b_data_width = 1,
		ram_block7a_4.port_b_first_address = 0,
		ram_block7a_4.port_b_first_bit_number = 4,
		ram_block7a_4.port_b_last_address = 127,
		ram_block7a_4.port_b_logical_ram_depth = 128,
		ram_block7a_4.port_b_logical_ram_width = 8,
		ram_block7a_4.port_b_read_enable_clock = "clock1",
		ram_block7a_4.ram_block_type = "AUTO",
		ram_block7a_4.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block7a_5
	( 
	.clk0(clock0),
	.clk1(clock1),
	.ena0(wren_a),
	.portaaddr({address_a_wire[6:0]}),
	.portadatain({data_a[5]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[6:0]}),
	.portbaddrstall(addressstall_b),
	.portbdataout(wire_ram_block7a_5portbdataout[0:0]),
	.portbre(1'b1)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portare(1'b1),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block7a_5.clk0_core_clock_enable = "ena0",
		ram_block7a_5.clk0_input_clock_enable = "none",
		ram_block7a_5.clk1_core_clock_enable = "none",
		ram_block7a_5.clk1_input_clock_enable = "none",
		ram_block7a_5.connectivity_checking = "OFF",
		ram_block7a_5.logical_ram_name = "ALTSYNCRAM",
		ram_block7a_5.mixed_port_feed_through_mode = "dont_care",
		ram_block7a_5.operation_mode = "dual_port",
		ram_block7a_5.port_a_address_width = 7,
		ram_block7a_5.port_a_data_width = 1,
		ram_block7a_5.port_a_first_address = 0,
		ram_block7a_5.port_a_first_bit_number = 5,
		ram_block7a_5.port_a_last_address = 127,
		ram_block7a_5.port_a_logical_ram_depth = 128,
		ram_block7a_5.port_a_logical_ram_width = 8,
		ram_block7a_5.port_b_address_clear = "none",
		ram_block7a_5.port_b_address_clock = "clock1",
		ram_block7a_5.port_b_address_width = 7,
		ram_block7a_5.port_b_data_out_clear = "none",
		ram_block7a_5.port_b_data_width = 1,
		ram_block7a_5.port_b_first_address = 0,
		ram_block7a_5.port_b_first_bit_number = 5,
		ram_block7a_5.port_b_last_address = 127,
		ram_block7a_5.port_b_logical_ram_depth = 128,
		ram_block7a_5.port_b_logical_ram_width = 8,
		ram_block7a_5.port_b_read_enable_clock = "clock1",
		ram_block7a_5.ram_block_type = "AUTO",
		ram_block7a_5.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block7a_6
	( 
	.clk0(clock0),
	.clk1(clock1),
	.ena0(wren_a),
	.portaaddr({address_a_wire[6:0]}),
	.portadatain({data_a[6]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[6:0]}),
	.portbaddrstall(addressstall_b),
	.portbdataout(wire_ram_block7a_6portbdataout[0:0]),
	.portbre(1'b1)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portare(1'b1),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block7a_6.clk0_core_clock_enable = "ena0",
		ram_block7a_6.clk0_input_clock_enable = "none",
		ram_block7a_6.clk1_core_clock_enable = "none",
		ram_block7a_6.clk1_input_clock_enable = "none",
		ram_block7a_6.connectivity_checking = "OFF",
		ram_block7a_6.logical_ram_name = "ALTSYNCRAM",
		ram_block7a_6.mixed_port_feed_through_mode = "dont_care",
		ram_block7a_6.operation_mode = "dual_port",
		ram_block7a_6.port_a_address_width = 7,
		ram_block7a_6.port_a_data_width = 1,
		ram_block7a_6.port_a_first_address = 0,
		ram_block7a_6.port_a_first_bit_number = 6,
		ram_block7a_6.port_a_last_address = 127,
		ram_block7a_6.port_a_logical_ram_depth = 128,
		ram_block7a_6.port_a_logical_ram_width = 8,
		ram_block7a_6.port_b_address_clear = "none",
		ram_block7a_6.port_b_address_clock = "clock1",
		ram_block7a_6.port_b_address_width = 7,
		ram_block7a_6.port_b_data_out_clear = "none",
		ram_block7a_6.port_b_data_width = 1,
		ram_block7a_6.port_b_first_address = 0,
		ram_block7a_6.port_b_first_bit_number = 6,
		ram_block7a_6.port_b_last_address = 127,
		ram_block7a_6.port_b_logical_ram_depth = 128,
		ram_block7a_6.port_b_logical_ram_width = 8,
		ram_block7a_6.port_b_read_enable_clock = "clock1",
		ram_block7a_6.ram_block_type = "AUTO",
		ram_block7a_6.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block7a_7
	( 
	.clk0(clock0),
	.clk1(clock1),
	.ena0(wren_a),
	.portaaddr({address_a_wire[6:0]}),
	.portadatain({data_a[7]}),
	.portadataout(),
	.portawe(wren_a),
	.portbaddr({address_b_wire[6:0]}),
	.portbaddrstall(addressstall_b),
	.portbdataout(wire_ram_block7a_7portbdataout[0:0]),
	.portbre(1'b1)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portare(1'b1),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block7a_7.clk0_core_clock_enable = "ena0",
		ram_block7a_7.clk0_input_clock_enable = "none",
		ram_block7a_7.clk1_core_clock_enable = "none",
		ram_block7a_7.clk1_input_clock_enable = "none",
		ram_block7a_7.connectivity_checking = "OFF",
		ram_block7a_7.logical_ram_name = "ALTSYNCRAM",
		ram_block7a_7.mixed_port_feed_through_mode = "dont_care",
		ram_block7a_7.operation_mode = "dual_port",
		ram_block7a_7.port_a_address_width = 7,
		ram_block7a_7.port_a_data_width = 1,
		ram_block7a_7.port_a_first_address = 0,
		ram_block7a_7.port_a_first_bit_number = 7,
		ram_block7a_7.port_a_last_address = 127,
		ram_block7a_7.port_a_logical_ram_depth = 128,
		ram_block7a_7.port_a_logical_ram_width = 8,
		ram_block7a_7.port_b_address_clear = "none",
		ram_block7a_7.port_b_address_clock = "clock1",
		ram_block7a_7.port_b_address_width = 7,
		ram_block7a_7.port_b_data_out_clear = "none",
		ram_block7a_7.port_b_data_width = 1,
		ram_block7a_7.port_b_first_address = 0,
		ram_block7a_7.port_b_first_bit_number = 7,
		ram_block7a_7.port_b_last_address = 127,
		ram_block7a_7.port_b_logical_ram_depth = 128,
		ram_block7a_7.port_b_logical_ram_width = 8,
		ram_block7a_7.port_b_read_enable_clock = "clock1",
		ram_block7a_7.ram_block_type = "AUTO",
		ram_block7a_7.lpm_type = "cycloneive_ram_block";
	assign
		address_a_wire = address_a,
		address_b_wire = address_b,
		q_b = {wire_ram_block7a_7portbdataout[0], wire_ram_block7a_6portbdataout[0], wire_ram_block7a_5portbdataout[0], wire_ram_block7a_4portbdataout[0], wire_ram_block7a_3portbdataout[0], wire_ram_block7a_2portbdataout[0], wire_ram_block7a_1portbdataout[0], wire_ram_block7a_0portbdataout[0]};
endmodule //FIFO_altsyncram


//dffpipe DELAY=1 WIDTH=8 clock d ALTERA_INTERNAL_OPTIONS=X_ON_VIOLATION_OPTION=OFF
//VERSION_BEGIN 16.0 cbx_a_gray2bin 2016:04:27:18:05:34:SJ cbx_a_graycounter 2016:04:27:18:05:34:SJ cbx_altdpram 2016:04:27:18:05:34:SJ cbx_altera_syncram 2016:04:27:18:05:34:SJ cbx_altera_syncram_nd_impl 2016:04:27:18:05:34:SJ cbx_altsyncram 2016:04:27:18:05:34:SJ cbx_cycloneii 2016:04:27:18:05:34:SJ cbx_dcfifo 2016:04:27:18:05:34:SJ cbx_fifo_common 2016:04:27:18:05:34:SJ cbx_lpm_add_sub 2016:04:27:18:05:34:SJ cbx_lpm_compare 2016:04:27:18:05:34:SJ cbx_lpm_counter 2016:04:27:18:05:34:SJ cbx_lpm_decode 2016:04:27:18:05:34:SJ cbx_lpm_mux 2016:04:27:18:05:34:SJ cbx_mgl 2016:04:27:18:06:48:SJ cbx_nadder 2016:04:27:18:05:34:SJ cbx_scfifo 2016:04:27:18:05:34:SJ cbx_stratix 2016:04:27:18:05:34:SJ cbx_stratixii 2016:04:27:18:05:34:SJ cbx_stratixiii 2016:04:27:18:05:34:SJ cbx_stratixv 2016:04:27:18:05:34:SJ cbx_util_mgl 2016:04:27:18:05:34:SJ  VERSION_END


//dffpipe DELAY=1 WIDTH=8 clock d q ALTERA_INTERNAL_OPTIONS=AUTO_SHIFT_REGISTER_RECOGNITION=OFF
//VERSION_BEGIN 16.0 cbx_mgl 2016:04:27:18:06:48:SJ cbx_stratixii 2016:04:27:18:05:34:SJ cbx_util_mgl 2016:04:27:18:05:34:SJ  VERSION_END

//synthesis_resources = reg 8 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
(* ALTERA_ATTRIBUTE = {"AUTO_SHIFT_REGISTER_RECOGNITION=OFF"} *)
module  FIFO_dffpipe
	( 
	clock,
	d,
	q) /* synthesis synthesis_clearbox=1 */;
	input   clock;
	input   [7:0]  d;
	output   [7:0]  q;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri0   clock;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	reg	[7:0]	dffe9a;
	wire clrn;
	wire ena;
	wire prn;
	wire sclr;

	// synopsys translate_off
	initial
		dffe9a = 0;
	// synopsys translate_on
	always @ ( posedge clock or  negedge prn or  negedge clrn)
		if (prn == 1'b0) dffe9a <= {8{1'b1}};
		else if (clrn == 1'b0) dffe9a <= 8'b0;
		else if  (ena == 1'b1)   dffe9a <= (d & {8{(~ sclr)}});
	assign
		clrn = 1'b1,
		ena = 1'b1,
		prn = 1'b1,
		q = dffe9a,
		sclr = 1'b0;
endmodule //FIFO_dffpipe

//synthesis_resources = reg 8 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
(* ALTERA_ATTRIBUTE = {"X_ON_VIOLATION_OPTION=OFF"} *)
module  FIFO_alt_synch_pipe
	( 
	clock,
	d,
	q) /* synthesis synthesis_clearbox=1 */;
	input   clock;
	input   [7:0]  d;
	output   [7:0]  q;

	wire  [7:0]   wire_dffpipe8_q;

	FIFO_dffpipe   dffpipe8
	( 
	.clock(clock),
	.d(d),
	.q(wire_dffpipe8_q));
	assign
		q = wire_dffpipe8_q;
endmodule //FIFO_alt_synch_pipe


//dffpipe DELAY=1 WIDTH=8 clock d q ALTERA_INTERNAL_OPTIONS=X_ON_VIOLATION_OPTION=OFF
//VERSION_BEGIN 16.0 cbx_a_gray2bin 2016:04:27:18:05:34:SJ cbx_a_graycounter 2016:04:27:18:05:34:SJ cbx_altdpram 2016:04:27:18:05:34:SJ cbx_altera_syncram 2016:04:27:18:05:34:SJ cbx_altera_syncram_nd_impl 2016:04:27:18:05:34:SJ cbx_altsyncram 2016:04:27:18:05:34:SJ cbx_cycloneii 2016:04:27:18:05:34:SJ cbx_dcfifo 2016:04:27:18:05:34:SJ cbx_fifo_common 2016:04:27:18:05:34:SJ cbx_lpm_add_sub 2016:04:27:18:05:34:SJ cbx_lpm_compare 2016:04:27:18:05:34:SJ cbx_lpm_counter 2016:04:27:18:05:34:SJ cbx_lpm_decode 2016:04:27:18:05:34:SJ cbx_lpm_mux 2016:04:27:18:05:34:SJ cbx_mgl 2016:04:27:18:06:48:SJ cbx_nadder 2016:04:27:18:05:34:SJ cbx_scfifo 2016:04:27:18:05:34:SJ cbx_stratix 2016:04:27:18:05:34:SJ cbx_stratixii 2016:04:27:18:05:34:SJ cbx_stratixiii 2016:04:27:18:05:34:SJ cbx_stratixv 2016:04:27:18:05:34:SJ cbx_util_mgl 2016:04:27:18:05:34:SJ  VERSION_END

//synthesis_resources = reg 8 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
(* ALTERA_ATTRIBUTE = {"X_ON_VIOLATION_OPTION=OFF"} *)
module  FIFO_alt_synch_pipe1
	( 
	clock,
	d,
	q) /* synthesis synthesis_clearbox=1 */;
	input   clock;
	input   [7:0]  d;
	output   [7:0]  q;

	wire  [7:0]   wire_dffpipe10_q;

	FIFO_dffpipe   dffpipe10
	( 
	.clock(clock),
	.d(d),
	.q(wire_dffpipe10_q));
	assign
		q = wire_dffpipe10_q;
endmodule //FIFO_alt_synch_pipe1


//lpm_compare DEVICE_FAMILY="Cyclone IV E" LPM_WIDTH=4 aeb dataa datab
//VERSION_BEGIN 16.0 cbx_cycloneii 2016:04:27:18:05:34:SJ cbx_lpm_add_sub 2016:04:27:18:05:34:SJ cbx_lpm_compare 2016:04:27:18:05:34:SJ cbx_mgl 2016:04:27:18:06:48:SJ cbx_nadder 2016:04:27:18:05:34:SJ cbx_stratix 2016:04:27:18:05:34:SJ cbx_stratixii 2016:04:27:18:05:34:SJ  VERSION_END

//synthesis_resources = 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
module  FIFO_cmpr
	( 
	aeb,
	dataa,
	datab) /* synthesis synthesis_clearbox=1 */;
	output   aeb;
	input   [3:0]  dataa;
	input   [3:0]  datab;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri0   [3:0]  dataa;
	tri0   [3:0]  datab;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	wire  [0:0]  aeb_result_wire;
	wire  [0:0]  aneb_result_wire;
	wire  [9:0]  data_wire;
	wire  eq_wire;

	assign
		aeb = eq_wire,
		aeb_result_wire = (~ aneb_result_wire),
		aneb_result_wire = (data_wire[0] | data_wire[1]),
		data_wire = {datab[3], dataa[3], datab[2], dataa[2], datab[1], dataa[1], datab[0], dataa[0], ((data_wire[6] ^ data_wire[7]) | (data_wire[8] ^ data_wire[9])), ((data_wire[2] ^ data_wire[3]) | (data_wire[4] ^ data_wire[5]))},
		eq_wire = aeb_result_wire;
endmodule //FIFO_cmpr


//lpm_mux DEVICE_FAMILY="Cyclone IV E" LPM_SIZE=2 LPM_WIDTH=1 LPM_WIDTHS=1 data result sel
//VERSION_BEGIN 16.0 cbx_lpm_mux 2016:04:27:18:05:34:SJ cbx_mgl 2016:04:27:18:06:48:SJ  VERSION_END

//synthesis_resources = lut 1 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
module  FIFO_mux
	( 
	data,
	result,
	sel) /* synthesis synthesis_clearbox=1 */;
	input   [1:0]  data;
	output   [0:0]  result;
	input   [0:0]  sel;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri0   [1:0]  data;
	tri0   [0:0]  sel;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	wire  [0:0]  result_node;
	wire  [0:0]  sel_node;
	wire  [1:0]  w_data311w;

	assign
		result = result_node,
		result_node = {((sel_node & w_data311w[1]) | ((~ sel_node) & w_data311w[0]))},
		sel_node = {sel[0]},
		w_data311w = {data[1:0]};
endmodule //FIFO_mux

//synthesis_resources = lut 4 M9K 1 reg 66 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
(* ALTERA_ATTRIBUTE = {"AUTO_SHIFT_REGISTER_RECOGNITION=OFF;REMOVE_DUPLICATE_REGISTERS=OFF;SYNCHRONIZER_IDENTIFICATION=OFF;SYNCHRONIZATION_REGISTER_CHAIN_LENGTH = 1;suppress_da_rule_internal=d101;suppress_da_rule_internal=d102;suppress_da_rule_internal=d103"} *)
module  FIFO_dcfifo
	( 
	data,
	q,
	rdclk,
	rdempty,
	rdreq,
	wrclk,
	wrfull,
	wrreq) /* synthesis synthesis_clearbox=1 */;
	input   [7:0]  data;
	output   [7:0]  q;
	input   rdclk;
	output   rdempty;
	input   rdreq;
	input   wrclk;
	output   wrfull;
	input   wrreq;

	wire  [7:0]   wire_rdptr_g1p_q;
	wire  [7:0]   wire_wrptr_g1p_q;
	wire  [7:0]   wire_fifo_ram_q_b;
	reg	[7:0]	delayed_wrptr_g;
	(* ALTERA_ATTRIBUTE = {"POWER_UP_LEVEL=HIGH"} *)
	reg	rdemp_eq_comp_lsb_aeb;
	(* ALTERA_ATTRIBUTE = {"POWER_UP_LEVEL=HIGH"} *)
	reg	rdemp_eq_comp_msb_aeb;
	reg	[7:0]	rdptr_g;
	reg	wrfull_eq_comp_lsb_mux_reg;
	reg	wrfull_eq_comp_msb_mux_reg;
	(* ALTERA_ATTRIBUTE = {"suppress_da_rule_internal=S102;POWER_UP_LEVEL=LOW"} *)
	reg	[7:0]	wrptr_g;
	wire  [7:0]   wire_rs_dgwp_q;
	wire  [7:0]   wire_ws_dgrp_q;
	wire  wire_rdempty_eq_comp1_lsb_aeb;
	wire  wire_rdempty_eq_comp1_msb_aeb;
	wire  wire_rdempty_eq_comp_lsb_aeb;
	wire  wire_rdempty_eq_comp_msb_aeb;
	wire  wire_wrfull_eq_comp1_lsb_aeb;
	wire  wire_wrfull_eq_comp1_msb_aeb;
	wire  wire_wrfull_eq_comp_lsb_aeb;
	wire  wire_wrfull_eq_comp_msb_aeb;
	wire  [0:0]   wire_rdemp_eq_comp_lsb_mux_result;
	wire  [0:0]   wire_rdemp_eq_comp_msb_mux_result;
	wire  [0:0]   wire_wrfull_eq_comp_lsb_mux_result;
	wire  [0:0]   wire_wrfull_eq_comp_msb_mux_result;
	wire  int_rdempty;
	wire  int_wrfull;
	wire  [6:0]  ram_address_a;
	wire  [6:0]  ram_address_b;
	wire  valid_rdreq;
	wire  valid_wrreq;
	wire  [7:0]  wrptr_g1s;
	wire  [7:0]  wrptr_gs;

	FIFO_a_graycounter   rdptr_g1p
	( 
	.clock(rdclk),
	.cnt_en(valid_rdreq),
	.q(wire_rdptr_g1p_q));
	FIFO_a_graycounter1   wrptr_g1p
	( 
	.clock(wrclk),
	.cnt_en(valid_wrreq),
	.q(wire_wrptr_g1p_q));
	FIFO_altsyncram   fifo_ram
	( 
	.address_a(ram_address_a),
	.address_b(ram_address_b),
	.addressstall_b((~ valid_rdreq)),
	.clock0(wrclk),
	.clock1(rdclk),
	.data_a(data),
	.q_b(wire_fifo_ram_q_b),
	.wren_a(valid_wrreq));
	// synopsys translate_off
	initial
		delayed_wrptr_g = 0;
	// synopsys translate_on
	always @ ( posedge wrclk)
		  delayed_wrptr_g <= wrptr_g;
	// synopsys translate_off
	initial
		rdemp_eq_comp_lsb_aeb = {1{1'b1}};
	// synopsys translate_on
	always @ ( posedge rdclk)
		  rdemp_eq_comp_lsb_aeb <= wire_rdemp_eq_comp_lsb_mux_result;
	// synopsys translate_off
	initial
		rdemp_eq_comp_msb_aeb = {1{1'b1}};
	// synopsys translate_on
	always @ ( posedge rdclk)
		  rdemp_eq_comp_msb_aeb <= wire_rdemp_eq_comp_msb_mux_result;
	// synopsys translate_off
	initial
		rdptr_g = 0;
	// synopsys translate_on
	always @ ( posedge rdclk)
		if (valid_rdreq == 1'b1)   rdptr_g <= wire_rdptr_g1p_q;
	// synopsys translate_off
	initial
		wrfull_eq_comp_lsb_mux_reg = 0;
	// synopsys translate_on
	always @ ( posedge wrclk)
		  wrfull_eq_comp_lsb_mux_reg <= wire_wrfull_eq_comp_lsb_mux_result;
	// synopsys translate_off
	initial
		wrfull_eq_comp_msb_mux_reg = 0;
	// synopsys translate_on
	always @ ( posedge wrclk)
		  wrfull_eq_comp_msb_mux_reg <= wire_wrfull_eq_comp_msb_mux_result;
	// synopsys translate_off
	initial
		wrptr_g = 0;
	// synopsys translate_on
	always @ ( posedge wrclk)
		if (valid_wrreq == 1'b1)   wrptr_g <= wire_wrptr_g1p_q;
	FIFO_alt_synch_pipe   rs_dgwp
	( 
	.clock(rdclk),
	.d(delayed_wrptr_g),
	.q(wire_rs_dgwp_q));
	FIFO_alt_synch_pipe1   ws_dgrp
	( 
	.clock(wrclk),
	.d(rdptr_g),
	.q(wire_ws_dgrp_q));
	FIFO_cmpr   rdempty_eq_comp1_lsb
	( 
	.aeb(wire_rdempty_eq_comp1_lsb_aeb),
	.dataa(delayed_wrptr_g[3:0]),
	.datab(wire_rdptr_g1p_q[3:0]));
	FIFO_cmpr   rdempty_eq_comp1_msb
	( 
	.aeb(wire_rdempty_eq_comp1_msb_aeb),
	.dataa(delayed_wrptr_g[7:4]),
	.datab(wire_rdptr_g1p_q[7:4]));
	FIFO_cmpr   rdempty_eq_comp_lsb
	( 
	.aeb(wire_rdempty_eq_comp_lsb_aeb),
	.dataa(delayed_wrptr_g[3:0]),
	.datab(rdptr_g[3:0]));
	FIFO_cmpr   rdempty_eq_comp_msb
	( 
	.aeb(wire_rdempty_eq_comp_msb_aeb),
	.dataa(delayed_wrptr_g[7:4]),
	.datab(rdptr_g[7:4]));
	FIFO_cmpr   wrfull_eq_comp1_lsb
	( 
	.aeb(wire_wrfull_eq_comp1_lsb_aeb),
	.dataa(rdptr_g[3:0]),
	.datab(wrptr_g1s[3:0]));
	FIFO_cmpr   wrfull_eq_comp1_msb
	( 
	.aeb(wire_wrfull_eq_comp1_msb_aeb),
	.dataa(rdptr_g[7:4]),
	.datab(wrptr_g1s[7:4]));
	FIFO_cmpr   wrfull_eq_comp_lsb
	( 
	.aeb(wire_wrfull_eq_comp_lsb_aeb),
	.dataa(rdptr_g[3:0]),
	.datab(wrptr_gs[3:0]));
	FIFO_cmpr   wrfull_eq_comp_msb
	( 
	.aeb(wire_wrfull_eq_comp_msb_aeb),
	.dataa(rdptr_g[7:4]),
	.datab(wrptr_gs[7:4]));
	FIFO_mux   rdemp_eq_comp_lsb_mux
	( 
	.data({wire_rdempty_eq_comp1_lsb_aeb, wire_rdempty_eq_comp_lsb_aeb}),
	.result(wire_rdemp_eq_comp_lsb_mux_result),
	.sel(valid_rdreq));
	FIFO_mux   rdemp_eq_comp_msb_mux
	( 
	.data({wire_rdempty_eq_comp1_msb_aeb, wire_rdempty_eq_comp_msb_aeb}),
	.result(wire_rdemp_eq_comp_msb_mux_result),
	.sel(valid_rdreq));
	FIFO_mux   wrfull_eq_comp_lsb_mux
	( 
	.data({wire_wrfull_eq_comp1_lsb_aeb, wire_wrfull_eq_comp_lsb_aeb}),
	.result(wire_wrfull_eq_comp_lsb_mux_result),
	.sel(valid_wrreq));
	FIFO_mux   wrfull_eq_comp_msb_mux
	( 
	.data({wire_wrfull_eq_comp1_msb_aeb, wire_wrfull_eq_comp_msb_aeb}),
	.result(wire_wrfull_eq_comp_msb_mux_result),
	.sel(valid_wrreq));
	assign
		int_rdempty = (rdemp_eq_comp_lsb_aeb & rdemp_eq_comp_msb_aeb),
		int_wrfull = (wrfull_eq_comp_lsb_mux_reg & wrfull_eq_comp_msb_mux_reg),
		q = wire_fifo_ram_q_b,
		ram_address_a = {(wrptr_g[7] ^ wrptr_g[6]), wrptr_g[5:0]},
		ram_address_b = {(wire_rdptr_g1p_q[7] ^ wire_rdptr_g1p_q[6]), wire_rdptr_g1p_q[5:0]},
		rdempty = int_rdempty,
		valid_rdreq = (rdreq & (~ int_rdempty)),
		valid_wrreq = (wrreq & (~ int_wrfull)),
		wrfull = int_wrfull,
		wrptr_g1s = {(~ wire_wrptr_g1p_q[7]), (~ wire_wrptr_g1p_q[6]), wire_wrptr_g1p_q[5:0]},
		wrptr_gs = {(~ wrptr_g[7]), (~ wrptr_g[6]), wrptr_g[5:0]};
endmodule //FIFO_dcfifo
//VALID FILE


// synopsys translate_off
`timescale 1 ps / 1 ps
// synopsys translate_on
module FIFO (
	data,
	rdclk,
	rdreq,
	wrclk,
	wrreq,
	q,
	rdempty,
	wrfull)/* synthesis synthesis_clearbox = 1 */;

	input	[7:0]  data;
	input	  rdclk;
	input	  rdreq;
	input	  wrclk;
	input	  wrreq;
	output	[7:0]  q;
	output	  rdempty;
	output	  wrfull;

	wire [7:0] sub_wire0;
	wire  sub_wire1;
	wire  sub_wire2;
	wire [7:0] q = sub_wire0[7:0];
	wire  rdempty = sub_wire1;
	wire  wrfull = sub_wire2;

	FIFO_dcfifo	FIFO_dcfifo_component (
				.data (data),
				.rdclk (rdclk),
				.rdreq (rdreq),
				.wrclk (wrclk),
				.wrreq (wrreq),
				.q (sub_wire0),
				.rdempty (sub_wire1),
				.wrfull (sub_wire2));

endmodule

// ============================================================
// CNX file retrieval info
// ============================================================
// Retrieval info: PRIVATE: AlmostEmpty NUMERIC "0"
// Retrieval info: PRIVATE: AlmostEmptyThr NUMERIC "-1"
// Retrieval info: PRIVATE: AlmostFull NUMERIC "0"
// Retrieval info: PRIVATE: AlmostFullThr NUMERIC "-1"
// Retrieval info: PRIVATE: CLOCKS_ARE_SYNCHRONIZED NUMERIC "1"
// Retrieval info: PRIVATE: Clock NUMERIC "4"
// Retrieval info: PRIVATE: Depth NUMERIC "128"
// Retrieval info: PRIVATE: Empty NUMERIC "1"
// Retrieval info: PRIVATE: Full NUMERIC "1"
// Retrieval info: PRIVATE: INTENDED_DEVICE_FAMILY STRING "Cyclone IV E"
// Retrieval info: PRIVATE: LE_BasedFIFO NUMERIC "0"
// Retrieval info: PRIVATE: LegacyRREQ NUMERIC "0"
// Retrieval info: PRIVATE: MAX_DEPTH_BY_9 NUMERIC "0"
// Retrieval info: PRIVATE: OVERFLOW_CHECKING NUMERIC "0"
// Retrieval info: PRIVATE: Optimize NUMERIC "2"
// Retrieval info: PRIVATE: RAM_BLOCK_TYPE NUMERIC "0"
// Retrieval info: PRIVATE: SYNTH_WRAPPER_GEN_POSTFIX STRING "1"
// Retrieval info: PRIVATE: UNDERFLOW_CHECKING NUMERIC "0"
// Retrieval info: PRIVATE: UsedW NUMERIC "1"
// Retrieval info: PRIVATE: Width NUMERIC "8"
// Retrieval info: PRIVATE: dc_aclr NUMERIC "0"
// Retrieval info: PRIVATE: diff_widths NUMERIC "0"
// Retrieval info: PRIVATE: msb_usedw NUMERIC "0"
// Retrieval info: PRIVATE: output_width NUMERIC "8"
// Retrieval info: PRIVATE: rsEmpty NUMERIC "1"
// Retrieval info: PRIVATE: rsFull NUMERIC "0"
// Retrieval info: PRIVATE: rsUsedW NUMERIC "0"
// Retrieval info: PRIVATE: sc_aclr NUMERIC "0"
// Retrieval info: PRIVATE: sc_sclr NUMERIC "0"
// Retrieval info: PRIVATE: wsEmpty NUMERIC "0"
// Retrieval info: PRIVATE: wsFull NUMERIC "1"
// Retrieval info: PRIVATE: wsUsedW NUMERIC "0"
// Retrieval info: LIBRARY: altera_mf altera_mf.altera_mf_components.all
// Retrieval info: CONSTANT: INTENDED_DEVICE_FAMILY STRING "Cyclone IV E"
// Retrieval info: CONSTANT: LPM_NUMWORDS NUMERIC "128"
// Retrieval info: CONSTANT: LPM_SHOWAHEAD STRING "ON"
// Retrieval info: CONSTANT: LPM_TYPE STRING "dcfifo"
// Retrieval info: CONSTANT: LPM_WIDTH NUMERIC "8"
// Retrieval info: CONSTANT: LPM_WIDTHU NUMERIC "7"
// Retrieval info: CONSTANT: OVERFLOW_CHECKING STRING "ON"
// Retrieval info: CONSTANT: RDSYNC_DELAYPIPE NUMERIC "3"
// Retrieval info: CONSTANT: UNDERFLOW_CHECKING STRING "ON"
// Retrieval info: CONSTANT: USE_EAB STRING "ON"
// Retrieval info: CONSTANT: WRSYNC_DELAYPIPE NUMERIC "3"
// Retrieval info: USED_PORT: data 0 0 8 0 INPUT NODEFVAL "data[7..0]"
// Retrieval info: USED_PORT: q 0 0 8 0 OUTPUT NODEFVAL "q[7..0]"
// Retrieval info: USED_PORT: rdclk 0 0 0 0 INPUT NODEFVAL "rdclk"
// Retrieval info: USED_PORT: rdempty 0 0 0 0 OUTPUT NODEFVAL "rdempty"
// Retrieval info: USED_PORT: rdreq 0 0 0 0 INPUT NODEFVAL "rdreq"
// Retrieval info: USED_PORT: wrclk 0 0 0 0 INPUT NODEFVAL "wrclk"
// Retrieval info: USED_PORT: wrfull 0 0 0 0 OUTPUT NODEFVAL "wrfull"
// Retrieval info: USED_PORT: wrreq 0 0 0 0 INPUT NODEFVAL "wrreq"
// Retrieval info: CONNECT: @data 0 0 8 0 data 0 0 8 0
// Retrieval info: CONNECT: @rdclk 0 0 0 0 rdclk 0 0 0 0
// Retrieval info: CONNECT: @rdreq 0 0 0 0 rdreq 0 0 0 0
// Retrieval info: CONNECT: @wrclk 0 0 0 0 wrclk 0 0 0 0
// Retrieval info: CONNECT: @wrreq 0 0 0 0 wrreq 0 0 0 0
// Retrieval info: CONNECT: q 0 0 8 0 @q 0 0 8 0
// Retrieval info: CONNECT: rdempty 0 0 0 0 @rdempty 0 0 0 0
// Retrieval info: CONNECT: wrfull 0 0 0 0 @wrfull 0 0 0 0
// Retrieval info: GEN_FILE: TYPE_NORMAL FIFO.v TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL FIFO.inc TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL FIFO.cmp TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL FIFO.bsf FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL FIFO_inst.v TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL FIFO_bb.v TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL FIFO_syn.v TRUE
// Retrieval info: LIB_FILE: altera_mf
